name: CI

on: [push]

jobs:
 sast_scan:
 # 執行 Bandit這個sast掃描工具
   name: Run Bandit Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
   # 檢查要掃描的程式碼
     uses: actions/checkout@v2
   # 安裝python，因為Bandit是一個python package
   - name: Set Python
     uses: actions/setup-python@v2
     with:
       python-version: 3.8
   
   - name: Install Bandit
     run: pip install bandit

   - name: Run Bandit Scan
   # .的意思為: 掃描文件夾裡面的所有內容
   # -f 輸出檔案格式 -o 檔名.輸出檔案格式
     run: bandit -ll -ii -r . -f json -o bandit-report.json

   # 保存記錄
   - name: Upload Artifact
     uses: actions/upload-artifact@v3
   # 遇到失敗(因為前面掃描到有漏洞就會以失敗而停止執行)也要執行後面的記錄保存步驟
     if: always()
     with:
      name: bandit-findings
      path: bandit-report.json
      
 # 建立另外一個獨立的程序
 image_scan:
   name: Build Image and Run Image Scan
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
   # 檢查要掃描的程式碼
     uses: actions/checkout@v2

   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Build Docker Image
     run: docker build -f Dockerfile -t myapp:latest .

   - name: Docker Scout Scan
     run: |
       curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
       sh install-scout.sh
       echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
       docker scout quickview
       docker scout cves
